name: "lets-get-triggered"
on:
  repository_dispatch:
    types: [run-it-ralph]
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      baselineTag: ${{ github.event.client_payload.baselinetag }}
      revision_number: ${{ github.event.client_payload.revision_number }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Run a one line script
        run: echo Hello, world
    
      - name: Run a multi line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo $baselineTag
          echo $revision_number

  